api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_task, name='add_task'),
]

server/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('api.urls')),
]

api/models.py
from django.db import models

class Task(models.Model):
    title = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

api/views.py
from django.shortcuts import render, redirect
from .models import Task

def index(request):
    tasks = Task.objects.all()
    return render(request, 'index.html', {'tasks': tasks})
    # return render(request, 'bas.html')

def add_task(request):
    if request.method == 'POST':
        title = request.POST.get('task_title')
        Task.objects.create(title=title)
    return redirect('api:index')

api/templates/index.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>To-Do List</title>

{% tailwind_css %}
    
</head>
<body class="bg-gray-50 font-serif leading-normal tracking-normal">
    <div class="m-52">
        <div class="flex items-center justify-center">
            <form action="{% url 'api:add_task' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="task_title" placeholder="Add a new task">
                <button type="submit">Add Task</button>
            </form>
        </div>
        <div class="flex items-center justify-center">
            <ul>
                {% for task in tasks %}
                    <li class="text-5xl flex items-center justify-center">{{ task.title }}{% if task.completed %} (Completed){% endif %}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>